name: "google/zx"
description: "Runs zx script"
branding:
  icon: "dollar-sign"
  color: "purple"
inputs:
  script:
    required: true
    description: "A script to execute"
runs:
  using: "composite"
  steps:
    - shell: basj
      run: |
        FORCE_COLOR=3 npx zx@6 << 'EOF'
        ${{inputs.script}}
        EOF
