name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: npm i
      - run: npm test
      - run: npm version ${{ github.event.release.tag_name }}
      - run: echo "//wombat-dressing-room.appspot.com/:_authToken=$AUTH_TOKEN" >> .npmrc
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}      
      - run: npm publish
      - run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
